// Brand code to name mapping based on Zalando data (updated 2025-09-18)
export const BRAND_CODE_TO_NAME: Record<string, string> = {
  "270": "274",
  "2Y2": "2Y Premium",
  "7D0": "7 DAYS Active",
  "7F1": "7 for all mankind",
  "ACG": "ACBC",
  "ACV": "Ace & Tate",
  "AS1": "ASICS",
  "AD7": "adidas by Stella McCartney",
  "TA4": "adidas Golf",
  "AD1": "adidas Originals",
  "AD5": "adidas Performance",
  "ADQ": "adidas Sportswear",
  "ADD": "Adidas Terrex",
  "AHM": "Adieu",
  "AEB": "AEVOR",
  "AHC": "Ahluwalia",
  "AI2": "Aigle",
  "2AI": "AIGNER",
  "AHW": "Alan Crocetti",
  "A5Q": "ALEKO",
  "ALK": "Alessandro Zavetti",
  "A80": "Allbirds",
  "A0Q": "AllSaints",
  "ALJ": "ALOHAS",
  "AL5": "Alpha Industries",
  "ALB": "Altra",
  "AM4": "American Eagle",
  "AT8": "American Tourister",
  "AM2": "American Vintage",
  "ANQ": "anello",
  "A18": "Antony Morato",
  "A15": "Arena",
  "ARU": "ARKET",
  "ARC": "Armani Exchange",
  "BA7": "Baldessarini",
  "BA2": "Barbour",
  "BG8": "Barbour International",
  "B57": "Bassetti",
  "B3R": "BAYTON",
  "QX7": "BDG Urban Outfitters",
  "B60": "Bell",
  "BE9": "Belstaff",
  "BE1": "Ben Sherman",
  "BE6": "Bench",
  "B14": "Berghaus",
  "BEJ": "Bershka",
  "BJ0": "Bianco",
  "BIJ": "BIDI BADU",
  "6BI": "Bikkembergs",
  "BI7": "Billabong",
  "BI1": "Birkenstock",
  "BJ2": "Björn Borg",
  "BM9": "Blauer",
  "BL5": "Blend",
  "BWT": "BLIZ",
  "BD8": "BLK DNM",
  "BVT": "BLKVIS",
  "3BL": "Blomus",
  "B67": "Bloomingville",
  "BO7": "Bogner",
  "F22": "Bogner Fire + Ice",
  "BWP": "BOILER ROOM",
  "B4L": "Born Living Yoga",
  "BB1": "BOSS",
  "HB1": "BOSS Home",
  "BR5": "Braun Büffel",
  "BRH": "Brave Soul",
  "BX0": "BRAX",
  "2BR": "Bric's",
  "B51": "Brixton",
  "BR3": "Bruuns Bazaar",
  "BWB": "brx by BRONX",
  "B43": "Buff",
  "BUB": "Buffalo London",
  "BU2": "Bullboxer",
  "B17": "Burton",
  "M08": "Burton Menswear London",
  "BYL": "ByON",
  "C6F": "C&A",
  "CF7": "Calida",
  "AX9": "Call it Spring",
  "CAW": "Callaway",
  "6CA": "Calvin Klein",
  "CK3": "Calvin Klein Collection",
  "CK4": "Calvin Klein Golf",
  "C18": "Calvin Klein Jeans",
  "CKA": "Calvin Klein Performance",
  "C17": "Calvin Klein Swimwear",
  "C51": "camano",
  "CA3": "Camper",
  "CAP": "Carlo Colucci",
  "14C": "Carrera",
  "C5I": "Castore",
  "C1A": "Casual Friday",
  "C2K": "Caterpillar",
  "C4A": "Champion Rochester",
  "CZ5": "CHASIN'",
  "C38": "Chiemsee",
  "CHZ": "CHIMI",
  "CW9": "CHPO",
  "CQQ": "Ciele",
  "CL1": "Clarks",
  "CL6": "Clarks Originals",
  "CLT": "Clarysse",
  "CLE": "Classics77",
  "CLB": "Cleptomanicx",
  "CL3": "CLOSED",
  "CLR": "CLOSURE London",
  "C70": "CMP",
  "COH": "COACH",
  "CO3": "Coccinelle",
  "C00": "Colmar",
  "CM0": "Colmar Originals",
  "C23": "Columbia",
  "CO4": "Converse",
  "COY": "Copenhagen Studios",
  "C1Q": "Cotton On",
  "IC7": "Cotton Soul",
  "C66": "Craft",
  "CX7": "Cristiano Ronaldo CR7",
  "CR4": "Crocs",
  "CR8": "Cross Sportswear",
  "CXA": "CXL by Christian Lacroix",
  "DA7": "Dakine",
  "D8W": "Damart",
  "0DC": "DC COMICS ORIGINALS",
  "DC1": "DC Shoes",
  "DD7": "DDDDD",
  "DK0": "Dekker",
  "DL3": "Delsey Paris",
  "DE4": "Denham",
  "DEO": "Denim Project",
  "DE1": "Desigual",
  "D47": "Deuter",
  "D29": "Diadora",
  "DI5": "Didriksons",
  "DI1": "Diesel",
  "DM1": "DIM",
  "DI2": "Disney",
  "DK1": "DKNY",
  "DO8": "DOCKERS",
  "DO1": "Dockers by Gerli",
  "D0E": "Doughnut",
  "DO2": "Dr. Martens",
  "DR1": "Dr.Denim",
  "4DR": "DreiMaster",
  "DR2": "DRYKORN",
  "2DS": "Dsquared2",
  "DU5": "Dune London",
  "EA7": "EA7 Emporio Armani",
  "EA0": "Each x Other",
  "EC1": "ECCO",
  "ECH": "ECCO LEATHER GOODS",
  "ECI": "ECKHAUS LATTA",
  "ECD": "Ecoalf",
  "ED2": "Ed Hardy",
  "ED1": "edc by Esprit",
  "EDN": "Edel-Optics",
  "ED3": "Edwin",
  "EIB": "EIGHTYFIVE",
  "EL8": "Element",
  "ELQ": "ELHO",
  "EL9": "Ellesse",
  "EA8": "Emporio Armani",
  "ENK": "Endless",
  "1ER": "Erima",
  "ES1": "Esprit",
  "ES4": "Esprit Collection",
  "2ET": "Eterna",
  "EY7": "EYTYS",
  "FA7": "Faguo",
  "FA1": "FALKE",
  "F0Q": "Family First",
  "FAV": "Fanatics",
  "FA5": "Farah",
  "F86": "FAVELA",
  "FIB": "Filling Pieces",
  "FI9": "Fiorucci",
  "FI3": "FitFlop",
  "FF0": "Flexfit",
  "F81": "Former",
  "FOQ": "forét",
  "FS1": "Fossil",
  "F7W": "Franchise",
  "F5X": "Friendly Shoes",
  "F11": "Fritzi aus Preußen",
  "F8A": "FROM FUTURE",
  "FUH": "Futah",
  "GS1": "G-STAR",
  "GSC": "G-Star Raw",
  "G50": "Gabba",
  "GA3": "GANT",
  "GP0": "GAP",
  "G16": "GAS",
  "GC9": "GCDS",
  "GE9": "Geospirit",
  "G52": "Gioseppo",
  "GI9": "Giro",
  "GLE": "Glorious Gangsta",
  "GM5": "GmbH",
  "GOG": "Good For Nothing",
  "GOC": "good morning",
  "G8F": "GripGrab",
  "GU1": "Guess",
  "HT6": "Hackett London",
  "H27": "Haglöfs",
  "HAJ": "HALO",
  "HA3": "Happy Socks",
  "HAN": "Hartmann",
  "H78": "Hatton Labs",
  "HA1": "Havaianas",
  "H26": "Hay",
  "HE7": "Head",
  "H5N": "Heathe",
  "DA8": "Hechter Paris",
  "HEC": "Heckett & Lane",
  "HE6": "Helly Hansen",
  "H15": "Herschel",
  "HI2": "HI-TEC",
  "H1X": "HOKA",
  "HO0": "Holzweiler",
  "HOO": "Houdini",
  "HOZ": "House Nordic",
  "H06": "House of Sunny",
  "H0H": "HUF",
  "HU7": "HUGO",
  "HU3": "Hummel",
  "HU8": "Hurley",
  "HV2": "HVISK",
  "HY5": "Hype",
  "ICO": "ICANIWILL",
  "IC3": "Iceberg",
  "IC6": "ICEBOUND",
  "CE6": "icebreaker",
  "IC1": "Icepeak",
  "CB9": "Icon Brand",
  "IE0": "iets frans...",
  "II0": "IIQUAL",
  "I13": "IN GOLD WE TRUST PARIS®",
  "IJ0": "INDICODE JEANS",
  "JL1": "J.LINDEBERG",
  "JL2": "J.LINDEBERG Sports",
  "JA2": "Jack & Jones",
  "JAT": "Jack & Jones Performance",
  "JAM": "Jack & Jones PREMIUM",
  "JA4": "Jack Wolfskin",
  "JAL": "Jack's Sportswear",
  "J3Z": "Jacker",
  "JL0": "Jaded London",
  "J32": "JAKO",
  "1JS": "JanSport",
  "4JE": "JEEP",
  "J23": "Johnstons of Elgin",
  "J33": "Joma",
  "JO9": "JOOP!",
  "JOG": "JOOP! Jeans",
  "JOC": "Jordan",
  "JO1": "Josef Seibel",
  "JO5": "Jost",
  "JU7": "Juicy Couture",
  "KS1": "K-SWISS",
  "KW1": "K-Way",
  "K39": "Kangol",
  "KAI": "Kaotiko",
  "K20": "Kaporal",
  "10K": "Kappa",
  "KK1": "Karl Kani",
  "K48": "KARL LAGERFELD",
  "KAO": "Kayori",
  "K0Q": "Kazar",
  "K0R": "Kazar Studio",
  "KE5": "Keen",
  "KE9": "Kempa",
  "K2Z": "KIABI",
  "KI1": "Kickers",
  "K13": "Killtec",
  "KIE": "Kings Will Dream",
  "1KI": "Kipling",
  "KJ1": "Kjus",
  "KLI": "KLABU",
  "KLH": "Klättermusen",
  "KN2": "KnowledgeCotton Apparel",
  "KD4": "Krüger Dirndl",
  "2LA": "La Martina",
  "LA2": "Lacoste",
  "L47": "Lacoste LIVE",
  "L06": "Lacoste Sport",
  "L17": "Lafuma",
  "9LA": "Laguiole",
  "5LA": "LANCASTER",
  "LAM": "Lancel",
  "LGW": "Last Resort AB",
  "LE1": "le coq sportif",
  "LS1": "Le Specs",
  "LE4": "Lee",
  "LRX": "Legacies",
  "LME": "LEGACY STUDIOS",
  "LG4": "LEGO",
  "L74": "LERROS",
  "LEP": "Les Deux",
  "L4Z": "Les Petits Basics",
  "LE2": "Levi's®",
  "LET": "Levi's® Engineered Jeans",
  "L1O": "Levi's® Extra",
  "LGU": "Levi's® Gold Tab",
  "L48": "Levi's® Made & Crafted",
  "LEY": "Levi's® Skateboarding",
  "LGV": "Levi's® Workwear",
  "LIQ": "Libertine-Libertine",
  "LG5": "Lindbergh",
  "LI6": "LIU JO",
  "LL1": "Lloyd",
  "1LJ": "LOIS Jeans",
  "L2G": "Lonsdale",
  "LRD": "Lorette Colé Duprat",
  "1LO": "Lotto",
  "L1R": "Lounge Nine",
  "LU0": "Lousy Livin Underwear",
  "LSA": "Love Scars",
  "LT1": "LTB",
  "LU9": "Luhta",
  "LY2": "Lyle & Scott",
  "M14": "Mads Nørgaard",
  "M4Z": "Maison Héritage",
  "MK9": "Makia",
  "04B": "Manastash",
  "M13": "Mandarina Duck",
  "M91": "Mango",
  "MJ4": "MARC JACOBS",
  "MA3": "Marc O'Polo",
  "OP5": "Marc O'Polo DENIM",
  "2GU": "MARCIANO BY GUESS",
  "M31": "Marco Tozzi",
  "MAY": "Maria Black",
  "M4K": "Marimekko",
  "C7A": "Market",
  "QM4": "Marks & Spencer",
  "MV2": "Marvel",
  "M38": "Mason's",
  "M60": "Matinique",
  "MA6": "Mavi",
  "MC2": "McGregor",
  "ME2": "Melvin & Hamilton",
  "MEF": "Mennace",
  "MEJ": "Merchcode",
  "ME1": "Merrell",
  "ME4": "Mexx",
  "1MI": "Michael Kors",
  "MIZ": "MICHAELIS",
  "M50": "Millet",
  "MI4": "Minimum",
  "MI1": "Minnetonka",
  "MCO": "MISHO",
  "6MI": "Missoni",
  "M6X": "Missoni Home",
  "M0M": "Mister Tee",
  "21M": "Mo",
  "MHR": "Modanisa",
  "MOX": "MODO by Roncato",
  "M45": "Moon Boot",
  "6MO": "MOSCHINO",
  "M52": "Mountain Hardwear",
  "M1F": "MR.BOHO",
  "MUF": "Mulberry",
  "MU3": "Mustang",
  "NA5": "NAF NAF",
  "NA6": "Napapijri",
  "NB3": "NBA",
  "N3T": "Nebbia",
  "ND8": "Neuw",
  "NE2": "New Balance",
  "NE3": "New Era",
  "NL0": "New Look",
  "1NE": "Newline",
  "NER": "Newport Bay Sailing Club",
  "NX3": "Next",
  "NIJ": "Night Addict",
  "NI4": "Nike Golf",
  "N12": "Nike Performance",
  "NS4": "Nike SB",
  "NI1": "Nike Sportswear",
  "NOK": "NO EXCESS",
  "NM3": "Noisy May",
  "NO6": "North Sails",
  "NOD": "North Star",
  "NB2": "Nubikk",
  "NU2": "Nudie Jeans",
  "R1V": "NY CONCEPT",
  "NE6": "NZA New Zealand Auckland",
  "OB9": "O Bag",
  "ON5": "O'Neill",
  "OA3": "Oakley",
  "OD1": "ODLO",
  "OL4": "OLYMP",
  "OL8": "OLYMP Level Five",
  "OL7": "OLYMP Luxor",
  "ONM": "On",
  "ONG": "On Vacation",
  "OS3": "Only & Sons",
  "OS4": "ONLY SHOES",
  "P52": "Original Penguin",
  "ORQ": "ORIGINALS BY JACK & JONES",
  "SR2": "Osprey",
  "P12": "Pajar",
  "P13": "Palladium",
  "PJ8": "Panafrica",
  "PA4": "Pantofola d'Oro",
  "PA6": "Papillio",
  "P14": "Patrizia Pepe",
  "PE4": "Peak Performance",
  "PE8": "Penfield",
  "PE1": "Pepe Jeans",
  "P8Z": "PEQUS",
  "P68": "Petrol Industries",
  "PB7": "Peuterey",
  "PHZ": "Pier One Sport",
  "P32": "Pierre Cardin",
  "PI8": "Pilgrim",
  "PIY": "Pius Gabor",
  "P0E": "PLUS EIGHTEEN",
  "PX8": "POC",
  "P50": "Pollini",
  "PO2": "Polo Ralph Lauren",
  "P1O": "Pompeii",
  "PD0": "Porsche Design",
  "PRO": "Primitive",
  "PRI": "PROFUOMO",
  "PS7": "PS Paul Smith",
  "PUC": "PULL&BEAR",
  "PU1": "Puma",
  "PU5": "Puma Golf",
  "QS1": "QS",
  "Q01": "QUAY AUSTRALIA",
  "QU1": "Quiksilver",
  "RW2": "R. M. WILLIAMS",
  "ROW": "R.D.D. ROYAL DENIM DIVISION",
  "RAD": "RAID",
  "RI0": "Rains",
  "R9J": "Rapha",
  "RBU": "Red Bull Racing x Pepe Jeans",
  "RET": "Red Bull SPECT Eyewear",
  "R06": "Redefined Rebel",
  "RE5": "Reebok",
  "RE0": "Reebok Classic",
  "RE2": "Reef",
  "R19": "Religion",
  "RE3": "Replay",
  "REW": "Rethink Stat",
  "RE6": "REVOLUTION",
  "RI7": "Rip Curl",
  "RI9": "River Island",
  "RV1": "RIVIERAS",
  "RL1": "RLX Golf",
  "1RO": "Roberto Cavalli",
  "4RO": "Roncato",
  "ROJ": "Rossignol",
  "RO5": "Roxy",
  "RV4": "RVCA",
  "SO2": "s.Oliver",
  "SOA": "s.Oliver BLACK LABEL",
  "S48": "Salamander",
  "SBI": "Salming",
  "SA5": "Salomon",
  "079": "Salomon Sportstyle",
  "SZ0": "Salsa Jeans",
  "SA3": "Samsøe Samsøe",
  "SV0": "Sandqvist",
  "SAD": "sandro",
  "7SA": "Santa Cruz",
  "S23": "Saucony",
  "SA7": "Saucony Originals",
  "S6S": "Saye",
  "S59": "Schiesser",
  "WD2": "Schmuddelwedda",
  "SC7": "Schöffel",
  "SC3": "Scotch & Soda",
  "SCY": "SCOTT Sports",
  "SEC": "Seahorse",
  "S5E": "Sean John",
  "SE2": "Sebago",
  "3SE": "Seidensticker",
  "SE6": "Selected Homme",
  "S16": "Sergio Tacchini",
  "S30": "Shepherd",
  "SIF": "SIKSILK",
  "7SI": "Sisley",
  "QS0": "Sister Jane",
  "SIB": "Sixth June",
  "SK1": "Skechers",
  "P07": "Skechers Performance",
  "SK2": "Skechers Sport",
  "SKD": "Skechers Wide Fit",
  "SL2": "Sloggi",
  "WO9": "Smartwool",
  "SMD": "Smilodox",
  "1SM": "Smith Optics",
  "SS9": "Sneaky Steve",
  "SO4": "Solid",
  "S1X": "SOULSTAR",
  "2SO": "Southpole",
  "SPJ": "Spect Eyewear",
  "1SP": "Speedo",
  "SY0": "Spyder",
  "04A": "Stan Ray",
  "T57": "Stance",
  "S2P": "STAPLE PIGEON",
  "X11": "Starter",
  "OA4": "State of Art",
  "SV5": "Stella Nova",
  "S90": "Stelton",
  "ST3": "Steve Madden",
  "OC4": "Stockerpoint",
  "7SO": "Stoneline",
  "S43": "Strellson",
  "ST1": "Strellson Premium",
  "S8R": "Studio Seidensticker",
  "SU2": "Superdry & Co",
  "SU1": "Superga",
  "SYG": "Sweet Protection",
  "ZS1": "Södahl",
  "TA1": "Tamaris",
  "TES": "Tealer",
  "TE4": "Ted Baker",
  "2TH": "The Bridge",
  "C5A": "The Couture Club",
  "TH3": "The North Face",
  "T3Q": "The Tracksuit Club",
  "TG0": "Tigha",
  "TI1": "Timberland",
  "TO2": "TOM TAILOR",
  "TO7": "TOM TAILOR DENIM",
  "TO1": "Tommy Hilfiger",
  "TOB": "Tommy Jeans",
  "TO3": "TOMS",
  "T1M": "Toni Pons",
  "TP8": "Topman",
  "TBB": "TravisMathew",
  "TRU": "Trendyol",
  "TRI": "TROLLKIDS",
  "T04": "Trussardi",
  "TU9": "TUFFSKULL",
  "1TU": "Tumi",
  "US2": "U.S. Polo Assn.",
  "UG1": "UGG",
  "UH1": "uhlsport",
  "UM1": "Umbro",
  "S75": "uncover by Schiesser",
  "UN2": "Under Armour",
  "4BE": "United Colors of Benetton",
  "UP7": "Upscale by Mister Tee",
  "UR6": "Urban Classics",
  "UV1": "Uvex",
  "5VA": "Valentino Bags",
  "VAQ": "Van Gils",
  "VL4": "van Laack",
  "VA2": "Vans",
  "VA6": "Vanzetti",
  "VA4": "Vaude",
  "V2T": "Venum",
  "1VE": "Versace",
  "1VJ": "Versace Jeans",
  "VEI": "Versace Jeans Couture",
  "VEN": "Vertere Berlin",
  "VI2": "Victoria Shoes",
  "V14": "Victorinox",
  "VIO": "Vintage Supply",
  "V19": "Volcom",
  "VD1": "Von Dutch",
  "WL3": "Walra",
  "WAT": "Wasted Paris",
  "WAM": "WAX LONDON",
  "WEB": "Weekday",
  "WIK": "Wild For The Weekend",
  "WI2": "Wilson",
  "WO8": "Woden",
  "WR1": "Wrangler",
  "WR8": "WRSTBHVR",
  "YEE": "Yeaz",
  "YO1": "YOURTURN",
  "Y0E": "Yourturn Kids",
  "ZI1": "Zign",
  "ZI4": "Zign Studio",
  "ZO8": "ZO! Home",
  "1ZO": "ZOO YORK",
  "ZW4": "Zwillingsherz"
}

export function getBrandNames(brandCodes: string[]): string {
  if (brandCodes.length === 0) {return 'Wszystkie marki'}

  const names = brandCodes.map(code => BRAND_CODE_TO_NAME[code] || code)
  if (names.length === 1) {return names[0]}
  if (names.length <= 3) {return names.join(', ')}

  return `${names.slice(0, 2).join(', ')} +${names.length - 2} więcej`
}

// Reverse mapping: from brand name to code
const NAME_TO_CODE_MAP = Object.fromEntries(
  Object.entries(BRAND_CODE_TO_NAME).map(([code, name]) => [name.toLowerCase(), code])
)

export function getBrandCodes(brandNames: string[]): string[] {
  return brandNames
    .map(name => NAME_TO_CODE_MAP[name.trim().toLowerCase()])
    .filter((code): code is string => code !== undefined)
}